name: YouNote build

on:
  push:
    branches:
      - home
      - dev
      - vls-36
      - vls-58
jobs:
  you-note-deploy:
    name: deploy YouNote
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/${{ secrets.USERNAME }}/frontend/2024_1_scratch_senior_devs && git pull
#      - name: Build frontend
#        uses: appleboy/ssh-action@master
#        with:
#          timeout: 10m
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          script: cd /home/${{ secrets.USERNAME }}/frontend/2024_1_scratch_senior_devs && sh ./build.sh
      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: npm run build
      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo cp -rf /home/${{ secrets.USERNAME}}/frontend/2024_1_scratch_senior_devs/dist/* /opt/public/
